In [47]:
#Abrir una base de datos para "Leer lo que contiene"
import pymongo
#import pandas as pd
from pymongo import MongoClient
client = MongoClient('127.0.0.1',27017)
db = client['DeberAnalisis']
db.create_collection('Bases')

CollectionInvalid: collection Bases already exists

In [48]:
from pymongo import MongoClient
client = MongoClient('127.0.0.1',27017)
print(client.list_database_names())

['DeberAnalisis', 'Fornite', 'Juegos', 'Peliculas', 'admin', 'config', 'local']

In [49]:
database = client.DeberAnalisis
collection = database.list_collection_names()
print(collection)

['Base', 'Bases']

In [6]:
import pymongo
import pandas as pd
from pymongo import MongoClient

# Conectar a MongoDB
client = MongoClient('127.0.0.1', 27017)
db = client['DeberAnalisis']
mi_coleccion = db['Base']

# Cargar el archivo CSV en un DataFrame
archivo_csv = 'Fortnite Statistics.csv'
df = pd.read_csv(archivo_csv)

# Convertir el DataFrame a una lista de diccionarios (cada fila es un diccionario)
datos_para_insertar = df.to_dict(orient='records')

# Insertar los documentos en la colecci√≥n
mi_coleccion.insert_many(datos_para_insertar)

InsertManyResult([ObjectId('6585bef52f798a280a3d460a'), ObjectId('6585bef52f798a280a3d460b'), ObjectId('6585bef52f798a280a3d460c'), ObjectId('6585bef52f798a280a3d460d'), ObjectId('6585bef52f798a280a3d460e'), ObjectId('6585bef52f798a280a3d460f'), ObjectId('6585bef52f798a280a3d4610'), ObjectId('6585bef52f798a280a3d4611'), ObjectId('6585bef52f798a280a3d4612'), ObjectId('6585bef52f798a280a3d4613'), ObjectId('6585bef52f798a280a3d4614'), ObjectId('6585bef52f798a280a3d4615'), ObjectId('6585bef52f798a280a3d4616'), ObjectId('6585bef52f798a280a3d4617'), ObjectId('6585bef52f798a280a3d4618'), ObjectId('6585bef52f798a280a3d4619'), ObjectId('6585bef52f798a280a3d461a'), ObjectId('6585bef52f798a280a3d461b'), ObjectId('6585bef52f798a280a3d461c'), ObjectId('6585bef52f798a280a3d461d'), ObjectId('6585bef52f798a280a3d461e'), ObjectId('6585bef52f798a280a3d461f'), ObjectId('6585bef52f798a280a3d4620'), ObjectId('6585bef52f798a280a3d4621'), ObjectId('6585bef52f798a280a3d4622'), ObjectId('6585bef52f798a280a3d4623'), ObjectId('6585bef52f798a280a3d4624'), ObjectId('6585bef52f798a280a3d4625'), ObjectId('6585bef52f798a280a3d4626'), ObjectId('6585bef52f798a280a3d4627'), ObjectId('6585bef52f798a280a3d4628'), ObjectId('6585bef52f798a280a3d4629'), ObjectId('6585bef52f798a280a3d462a'), ObjectId('6585bef52f798a280a3d462b'), ObjectId('6585bef52f798a280a3d462c'), ObjectId('6585bef52f798a280a3d462d'), ObjectId('6585bef52f798a280a3d462e'), ObjectId('6585bef52f798a280a3d462f'), ObjectId('6585bef52f798a280a3d4630'), ObjectId('6585bef52f798a280a3d4631'), ObjectId('6585bef52f798a280a3d4632'), ObjectId('6585bef52f798a280a3d4633'), ObjectId('6585bef52f798a280a3d4634'), ObjectId('6585bef52f798a280a3d4635'), ObjectId('6585bef52f798a280a3d4636'), ObjectId('6585bef52f798a280a3d4637'), ObjectId('6585bef52f798a280a3d4638'), ObjectId('6585bef52f798a280a3d4639'), ObjectId('6585bef52f798a280a3d463a'), ObjectId('6585bef52f798a280a3d463b'), ObjectId('6585bef52f798a280a3d463c'), ObjectId('6585bef52f798a280a3d463d'), ObjectId('6585bef52f798a280a3d463e'), ObjectId('6585bef52f798a280a3d463f'), ObjectId('6585bef52f798a280a3d4640'), ObjectId('6585bef52f798a280a3d4641'), ObjectId('6585bef52f798a280a3d4642'), ObjectId('6585bef52f798a280a3d4643'), ObjectId('6585bef52f798a280a3d4644'), ObjectId('6585bef52f798a280a3d4645'), ObjectId('6585bef52f798a280a3d4646'), ObjectId('6585bef52f798a280a3d4647'), ObjectId('6585bef52f798a280a3d4648'), ObjectId('6585bef52f798a280a3d4649'), ObjectId('6585bef52f798a280a3d464a'), ObjectId('6585bef52f798a280a3d464b'), ObjectId('6585bef52f798a280a3d464c'), ObjectId('6585bef52f798a280a3d464d'), ObjectId('6585bef52f798a280a3d464e'), ObjectId('6585bef52f798a280a3d464f'), ObjectId('6585bef52f798a280a3d4650'), ObjectId('6585bef52f798a280a3d4651'), ObjectId('6585bef52f798a280a3d4652'), ObjectId('6585bef52f798a280a3d4653'), ObjectId('6585bef52f798a280a3d4654'), ObjectId('6585bef52f798a280a3d4655'), ObjectId('6585bef52f798a280a3d4656'), ObjectId('6585bef52f798a280a3d4657'), ObjectId('6585bef52f798a280a3d4658'), ObjectId('6585bef52f798a280a3d4659'), ObjectId('6585bef52f798a280a3d465a'), ObjectId('6585bef52f798a280a3d465b'), ObjectId('6585bef52f798a280a3d465c'), ObjectId('6585bef52f798a280a3d465d'), ObjectId('6585bef52f798a280a3d465e'), ObjectId('6585bef52f798a280a3d465f'), ObjectId('6585bef52f798a280a3d4660')], acknowledged=True)

In [75]:
import pymongo
import pandas as pd
from pymongo import MongoClient
client = MongoClient()
db = client.DeberAnalisis
collection = db.Base
data1 = pd.DataFrame(list(collection.find()))#.drop('_id', axis=1)

In [76]:
data1

,_id,Date,Time of Day,Placed,Mental State,Eliminations,Assists,Revives,Accuracy,Hits,Head Shots,Distance Traveled,Materials Gathered,Materials Used,Damage Taken,Damage to Players,Damage to Structures
0,6585bef52f798a280a3d460a,4/10,6:00 PM,27,sober,2,0,0,23%,14,2,271.08,20,20,272,331,621
1,6585bef52f798a280a3d460b,4/10,6:00 PM,45,sober,1,2,0,30%,19,1,396.73,123,30,247,444,998
2,6585bef52f798a280a3d460c,4/10,6:00 PM,38,high,3,0,0,30%,32,1,607.80,71,60,176,322,1109
3,6585bef52f798a280a3d460d,4/10,7:00 PM,30,high,1,3,0,18%,19,1,714.16,244,10,238,330,4726
4,6585bef52f798a280a3d460e,4/10,7:00 PM,16,high,3,1,1,58%,42,18,1140.00,584,150,365,668,2070
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
83,6585bef52f798a280a3d465d,17-Apr,12:00 AM,24,high,4,0,0,20%,12,4,222.54,94,0,96,478,2262
84,6585bef52f798a280a3d465e,17-Apr,1:00 PM,30,sober,1,2,0,28%,40,4,267.00,78,30,148,375,1196
85,6585bef52f798a280a3d465f,17-Apr,2:00 PM,18,sober,3,2,1,26%,25,3,954.43,370,60,354,475,1168
86,6585bef52f798a280a3d4660,17-Apr,2:00 PM,39,sober,1,0,0,31%,12,1,226.67,75,0,120,338,1105
87,6585c9b02f798a280a3d467a,19/03,8:58 PM,10,Alto,1,10,1,50%,10,1,110.10,1000,10,100,100,10000

In [71]:
ingreso_dato=[{
    "Date":"19/03",
    "Time of Day":"8:58 PM",
    "Placed":50,
    "Mental State":"Alto",
    "Eliminations":5,
    "Assists":10,
    "Revives":3,
    "Accuracy":"50%",
    "Hits":50,
    "Head Shots":5,
    "Distance Traveled":550.50,
    "Materials Gathered":5000,
    "Materials Used":50,
    "Damage Taken":500,
    "Damage to Players":500,
    "Damage to Structures":500,
},{"Date":"19/03",
    "Time of Day":"8:58 PM",
    "Placed":10,
    "Mental State":"Alto",
    "Eliminations":1,
    "Assists":10,
    "Revives":1,
    "Accuracy":"50%",
    "Hits":10,
    "Head Shots":1,
    "Distance Traveled":110.10,
    "Materials Gathered":1000,
    "Materials Used":10,
    "Damage Taken":100,
    "Damage to Players":100,
    "Damage to Structures":10000,}]
resultado=collection.insert_many(ingreso_dato)

In [74]:
from bson.objectid import ObjectId
eliminar={'_id':ObjectId('6585c9b02f798a280a3d4679')}
collection.delete_one(eliminar)

DeleteResult({'n': 1, 'ok': 1.0}, acknowledged=True)

In [57]:
actualizar={'_id':ObjectId('6585bf1c2f798a280a3d4662')}
cambiar_valores={'$set':{'Assists':'xdxd'}}
collection.update_one(actualizar, cambiar_valores)

UpdateResult({'n': 1, 'nModified': 0, 'ok': 1.0, 'updatedExisting': True}, acknowledged=True)

In [70]:
data1[(data1['Assists']==2)&(data1['Hits']<=14)&(data1['Revives']>=1)]

,_id,Date,Time of Day,Placed,Mental State,Eliminations,Assists,Revives,Accuracy,Hits,Head Shots,Distance Traveled,Materials Gathered,Materials Used,Damage Taken,Damage to Players,Damage to Structures
73,6585bef52f798a280a3d4653,4/15,5:00 PM,15,high,2,2,1,10%,13,4,792.0,118,110,313,471,3383

In [17]:
data1[(data1['Placed']==27)&(data1['Materials Used']==10)]

Empty DataFrame
Columns: [_id, Date, Time of Day, Placed, Mental State, Eliminations, Assists, Revives, Accuracy, Hits, Head Shots, Distance Traveled, Materials Gathered, Materials Used, Damage Taken, Damage to Players, Damage to Structures]
Index: []

In [19]:
data1[(data1['Eliminations']>=2)&(data1['Placed']<=15)&(data1['Revives']==2)]

,_id,Date,Time of Day,Placed,Mental State,Eliminations,Assists,Revives,Accuracy,Hits,Head Shots,Distance Traveled,Materials Gathered,Materials Used,Damage Taken,Damage to Players,Damage to Structures
79,6584f11eea0586f01b7dc6a4,4/15,11:00 PM,4,sober,5,2,2,42%,52,0,3550.0,850,450,436,724,1377

In [22]:
data1[(data1['Date']=='4/15')&(data1['Damage Taken']>=100)].head(3)

,_id,Date,Time of Day,Placed,Mental State,Eliminations,Assists,Revives,Accuracy,Hits,Head Shots,Distance Traveled,Materials Gathered,Materials Used,Damage Taken,Damage to Players,Damage to Structures
67,6584f11eea0586f01b7dc698,4/15,1:00 PM,17,sober,2,0,0,27%,32,1,1650.0,317,160,270,502,2029
68,6584f11eea0586f01b7dc699,4/15,1:00 PM,13,sober,6,2,0,13%,38,7,1890.0,1560,140,367,1005,9540
69,6584f11eea0586f01b7dc69a,4/15,2:00 PM,5,sober,6,3,0,11%,29,3,3350.0,421,230,366,764,11077

In [23]:
data1[(data1['Placed']>=10)&(data1['Distance Traveled']>=1500)&(data1['Revives']==0)].tail()

,_id,Date,Time of Day,Placed,Mental State,Eliminations,Assists,Revives,Accuracy,Hits,Head Shots,Distance Traveled,Materials Gathered,Materials Used,Damage Taken,Damage to Players,Damage to Structures
17,6584f11eea0586f01b7dc666,4/11,2:00 PM,20,sober,1,6,0,23%,19,2,1650.0,62,60,315,611,3506
33,6584f11eea0586f01b7dc676,4/13,3:00 PM,14,sober,1,2,0,12%,11,4,1700.0,519,60,316,416,8412
36,6584f11eea0586f01b7dc679,4/13,7:00 PM,10,high,3,3,0,22%,48,5,1810.0,512,150,567,651,2371
37,6584f11eea0586f01b7dc67a,4/13,7:00 PM,13,high,6,0,0,36%,92,22,1500.0,894,160,257,1253,4871
46,6584f11eea0586f01b7dc683,4/14,1:00 PM,11,sober,2,1,0,17%,24,2,1980.0,970,70,274,335,5948
60,6584f11eea0586f01b7dc691,4/14,4:00 PM,12,high,3,0,0,25%,25,9,1950.0,204,50,352,481,2511
67,6584f11eea0586f01b7dc698,4/15,1:00 PM,17,sober,2,0,0,27%,32,1,1650.0,317,160,270,502,2029
68,6584f11eea0586f01b7dc699,4/15,1:00 PM,13,sober,6,2,0,13%,38,7,1890.0,1560,140,367,1005,9540

In [78]:
data1[(data1['Hits'] >= 25) & (data1['Head Shots'] < 10) | (data1['Materials Used'])]

,_id,Date,Time of Day,Placed,Mental State,Eliminations,Assists,Revives,Accuracy,Hits,Head Shots,Distance Traveled,Materials Gathered,Materials Used,Damage Taken,Damage to Players,Damage to Structures
0,6585bef52f798a280a3d460a,4/10,6:00 PM,27,sober,2,0,0,23%,14,2,271.08,20,20,272,331,621
1,6585bef52f798a280a3d460b,4/10,6:00 PM,45,sober,1,2,0,30%,19,1,396.73,123,30,247,444,998
2,6585bef52f798a280a3d460c,4/10,6:00 PM,38,high,3,0,0,30%,32,1,607.80,71,60,176,322,1109
3,6585bef52f798a280a3d460d,4/10,7:00 PM,30,high,1,3,0,18%,19,1,714.16,244,10,238,330,4726
4,6585bef52f798a280a3d460e,4/10,7:00 PM,16,high,3,1,1,58%,42,18,1140.00,584,150,365,668,2070
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
81,6585bef52f798a280a3d465b,16-Apr,11:00 PM,17,high,3,2,2,33%,65,20,752.64,62,60,202,1222,2200
82,6585bef52f798a280a3d465c,17-Apr,12:00 AM,2,high,8,2,0,31%,97,8,3770.00,1750,400,576,1492,4593
84,6585bef52f798a280a3d465e,17-Apr,1:00 PM,30,sober,1,2,0,28%,40,4,267.00,78,30,148,375,1196
85,6585bef52f798a280a3d465f,17-Apr,2:00 PM,18,sober,3,2,1,26%,25,3,954.43,370,60,354,475,1168
87,6585c9b02f798a280a3d467a,19/03,8:58 PM,10,Alto,1,10,1,50%,10,1,110.10,1000,10,100,100,10000

In [94]:
data1[(data1['Damage to Structures'] > 1000) & (data1['Head Shots'] > 5)].tail(4)

,_id,Date,Time of Day,Placed,Mental State,Eliminations,Assists,Revives,Accuracy,Hits,Head Shots,Distance Traveled,Materials Gathered,Materials Used,Damage Taken,Damage to Players,Damage to Structures
68,6585bef52f798a280a3d464e,4/15,1:00 PM,13,sober,6,2,0,13%,38,7,1890.00,1560,140,367,1005,9540
76,6585bef52f798a280a3d4656,4/15,10:00 PM,15,sober,3,0,1,36%,83,13,336.46,175,10,223,1014,2434
81,6585bef52f798a280a3d465b,16-Apr,11:00 PM,17,high,3,2,2,33%,65,20,752.64,62,60,202,1222,2200
82,6585bef52f798a280a3d465c,17-Apr,12:00 AM,2,high,8,2,0,31%,97,8,3770.00,1750,400,576,1492,4593

In [95]:
data1[(data1['Revives'] > 1) & (data1['Mental State'] == 'high')].head(3)

,_id,Date,Time of Day,Placed,Mental State,Eliminations,Assists,Revives,Accuracy,Hits,Head Shots,Distance Traveled,Materials Gathered,Materials Used,Damage Taken,Damage to Players,Damage to Structures
40,6585bef52f798a280a3d4632,4/13,8:00 PM,16,high,4,2,2,23%,28,2,526.50,153,20,142,922,2220
80,6585bef52f798a280a3d465a,16-Apr,10:00 PM,24,high,1,1,2,64%,7,2,249.22,108,0,196,468,1590
81,6585bef52f798a280a3d465b,16-Apr,11:00 PM,17,high,3,2,2,33%,65,20,752.64,62,60,202,1222,2200

In [ ]:
data1[(data1['Eliminations'] < 3) & (data1['Placed'] < 25) | (data1['Damage']].head(3)